### ISSUE TITLE
Support inline doc tags

### ISSUE THREAD

**Issue by Kroc** [burodepeper/minimal-syntax#9]
E.g.

``` php
/** @var set this to something */
public $nothing;
```

The tag doesn't get coloured as it does in a larger doc block, i.e.

``` php
/**
 * @var set this to something
*/
public $nothing;
```

Ironically GitHub also gets this wrong.

P.S. Absolutely love this theme, keep up the great work!

**Comment by burodepeper** [comment]
Hi @Kroc, first of all, thanks for the compliment!

As for your issue, I'm afraid it is due how `language-php` parses the php code. My theme doesn't do any parsing of its own, just colors elements that are exposed by the grammar parser.

See https://github.com/atom/language-php/blob/master/grammars/php.cson#L160-218 and more in particular https://github.com/atom/language-php/blob/master/grammars/php.cson#L167. The included `#php_doc` only works when the first line of a comment (block) is `/**`. I don't see why it can't be included in single line comments, so I suggest you create an issue about [over there](https://github.com/atom/language-php/issues).

On a side-note, I'm keeping this issue open, because I don't like the blue on orange in the comments ; )

![schermafbeelding 2016-04-26 om 10 58 09](https://cloud.githubusercontent.com/assets/3703530/14812512/cba92d9a-0b9d-11e6-9302-60f9f70e4277.png)

**Comment by Kroc** [comment]
I've submitted changes to the PHP language grammar, and if those get accepted, then I will be able to solve the single-line docblock problem too.
